/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const ColumnModel = (props: any) => {
    const group = useRef()
    const data: any = useGLTF('/models/Pilar.gltf')
    console.log("data", data)
    return (
        <group ref={group} {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={data.nodes.Pillar2.geometry}
                material={data.materials['lambert2']}
                rotation={[Math.PI / 2, 0, 0]}
                position={[0, 2, 0]}
                scale={[0.25, 0.25, 0.25]}
            />
        </group>
    )
}

useGLTF.preload('/models/Pilar.gltf')

export default ColumnModel;